# Generated by Django 5.1.3 on 2024-11-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanagement", "0002_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
