# Generated by Django 5.1.3 on 2024-11-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanagement", "0003_issue_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="assignee",
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projectmanagement.project",
            ),
            preserve_default=False,
        ),
    ]
